In [71]:
#予測精度（0.99828）

In [72]:
import keras
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.optimizers import RMSprop

In [73]:
from keras.datasets import mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()

In [74]:
#batch_size = 128
#epochs = 50
num_classes = 10

In [75]:
x_train = x_train.reshape(60000, 784)
x_test = x_test.reshape(10000, 784)

In [76]:
x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train /= 255
x_test /= 255

In [77]:
y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)

In [78]:
activation = "relu"
out_dim = 1024
dropout = 0.2
batch_size = 256
epochs = 110

In [ ]:

'''
予測精度（0.99828）時のパラメータ
activation = "relu"#
out_dim = 1024
dropout = 0.2
batch_size = 256
epochs = 110
model  = Sequential()
model.add(Dense(1024, activation = 'relu', input_shape = (784,)))
model.add(Dropout(dropout))
model.add(Dense(out_dim, activation = 'relu'))
model.add(Dropout(dropout))
model.add(Dense(10, activation = 'softmax'))
model.summary()
model.compile(loss='categorical_crossentropy', optimizer=RMSprop(lr=0.0009), metrics=['accuracy'])

'''

In [79]:
model  = Sequential()
model.add(Dense(1024, activation = 'relu', input_shape = (784,)))
model.add(Dropout(dropout))
model.add(Dense(1024, activation = 'relu'))
model.add(Dropout(dropout))
model.add(Dense(10, activation = 'softmax'))
model.summary()
model.compile(loss='categorical_crossentropy', optimizer=RMSprop(lr=0.0009), metrics=['accuracy'])

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_31 (Dense)             (None, 1024)              803840    
_________________________________________________________________
dropout_21 (Dropout)         (None, 1024)              0         
_________________________________________________________________
dense_32 (Dense)             (None, 1024)              1049600   
_________________________________________________________________
dropout_22 (Dropout)         (None, 1024)              0         
_________________________________________________________________
dense_33 (Dense)             (None, 10)                10250     
Total params: 1,863,690
Trainable params: 1,863,690
Non-trainable params: 0
_________________________________________________________________


In [80]:
history = model.fit(x_train, y_train
                   , batch_size = batch_size
                    , epochs = epochs
                    , verbose = 1
                    , validation_data=(x_test, y_test))

Train on 60000 samples, validate on 10000 samples
Epoch 1/110
60000/60000 [==============================] - 265s 4ms/step - loss: 0.2628 - acc: 0.9188 - val_loss: 0.1520 - val_acc: 0.9515
Epoch 2/110
60000/60000 [==============================] - 258s 4ms/step - loss: 0.0969 - acc: 0.9704 - val_loss: 0.1009 - val_acc: 0.9677
Epoch 3/110
60000/60000 [==============================] - 255s 4ms/step - loss: 0.0666 - acc: 0.9793 - val_loss: 0.0827 - val_acc: 0.9743
Epoch 4/110
60000/60000 [==============================] - 257s 4ms/step - loss: 0.0491 - acc: 0.9845 - val_loss: 0.1333 - val_acc: 0.9623
Epoch 5/110
60000/60000 [==============================] - 258s 4ms/step - loss: 0.0390 - acc: 0.9882 - val_loss: 0.0635 - val_acc: 0.9819
Epoch 6/110
60000/60000 [==============================] - 256s 4ms/step - loss: 0.0327 - acc: 0.9899 - val_loss: 0.0759 - val_acc: 0.9801
Epoch 7/110
60000/60000 [==============================] - 257s 4ms/step - loss: 0.0287 - acc: 0.9906 - val_loss: 0.

In [81]:
import pandas as pd
test = pd.read_csv("test.csv")

In [82]:
print(test.shape)

(28000, 784)


In [83]:
y_pred = model.predict(test)

In [84]:
print(y_pred)

[[0. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 1. ... 0. 0. 0.]]


In [85]:
result= [0]*28000

for y, item in enumerate(y_pred):
    for x, name in enumerate(item):
        if name == 1:
            result[y] = x
            break

In [86]:
print(result[0:12])

[2, 0, 9, 0, 3, 7, 0, 3, 0, 3, 5, 7]


In [87]:
print(len(result))
submit_list = result

28000


In [88]:
import numpy as np
imgid = np.array(np.arange(1,28001)).astype(int)
result = pd.DataFrame(submit_list, imgid, columns = ["Label"])
result.index.name = "ImageId"
result.to_csv("digits_result12.csv")

In [89]:
print(result)

         Label
ImageId       
1            2
2            0
3            9
4            0
5            3
6            7
7            0
8            3
9            0
10           3
11           5
12           7
13           4
14           0
15           4
16           3
17           3
18           1
19           9
20           0
21           9
22           1
23           1
24           5
25           7
26           4
27           2
28           7
29           4
30           7
...        ...
27971        5
27972        0
27973        4
27974        8
27975        0
27976        3
27977        6
27978        0
27979        1
27980        9
27981        3
27982        1
27983        1
27984        0
27985        4
27986        5
27987        2
27988        2
27989        9
27990        6
27991        7
27992        6
27993        1
27994        9
27995        7
27996        9
27997        7
27998        3
27999        9
28000        2

[28000 rows x 1 columns]
