In [1]:
#バッチごとに後に正規化

In [2]:
import keras
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout, BatchNormalization
from keras.optimizers import RMSprop

Using TensorFlow backend.


In [3]:
from keras.datasets import mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()

In [4]:
#batch_size = 128
#epochs = 50
num_classes = 10

In [5]:
x_train = x_train.reshape(60000, 784)
x_test = x_test.reshape(10000, 784)

In [6]:
x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train /= 255
x_test /= 255

In [7]:
y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)

In [37]:
activation = "relu"
out_dim = 256
dropout = 0.2
batch_size = 128
epochs = 115

In [49]:
model  = Sequential()
model.add(Dense(256, activation = 'relu', input_shape = (784,)))
model.add(Dropout(dropout))
model.add(BatchNormalization())
model.add(Dense(256, activation = 'relu'))
model.add(Dropout(dropout))
model.add(Dense(10, activation = 'softmax'))
model.summary()
model.compile(loss='categorical_crossentropy', optimizer=RMSprop(lr=0.0009), metrics=['accuracy'])

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_13 (Dense)             (None, 256)               200960    
_________________________________________________________________
dropout_9 (Dropout)          (None, 256)               0         
_________________________________________________________________
batch_normalization_9 (Batch (None, 256)               1024      
_________________________________________________________________
dense_14 (Dense)             (None, 256)               65792     
_________________________________________________________________
dropout_10 (Dropout)         (None, 256)               0         
_________________________________________________________________
dense_15 (Dense)             (None, 10)                2570      
Total params: 270,346
Trainable params: 269,834
Non-trainable params: 512
_________________________________________________________________


In [50]:
history = model.fit(x_train, y_train
                   , batch_size = batch_size
                    , epochs = epochs
                    , verbose = 1
                    , validation_data=(x_test, y_test))

Train on 60000 samples, validate on 10000 samples
Epoch 1/115
60000/60000 [==============================] - 74s 1ms/step - loss: 0.2536 - acc: 0.9226 - val_loss: 0.1128 - val_acc: 0.9642
Epoch 2/115
60000/60000 [==============================] - 67s 1ms/step - loss: 0.1228 - acc: 0.9634 - val_loss: 0.0850 - val_acc: 0.9757
Epoch 3/115
60000/60000 [==============================] - 68s 1ms/step - loss: 0.0946 - acc: 0.9713 - val_loss: 0.0798 - val_acc: 0.9764
Epoch 4/115
60000/60000 [==============================] - 66s 1ms/step - loss: 0.0795 - acc: 0.9759 - val_loss: 0.0790 - val_acc: 0.9776
Epoch 5/115
60000/60000 [==============================] - 68s 1ms/step - loss: 0.0711 - acc: 0.9787 - val_loss: 0.0795 - val_acc: 0.9771
Epoch 6/115
60000/60000 [==============================] - 68s 1ms/step - loss: 0.0617 - acc: 0.9810 - val_loss: 0.0770 - val_acc: 0.9785
Epoch 7/115
60000/60000 [==============================] - 68s 1ms/step - loss: 0.0562 - acc: 0.9830 - val_loss: 0.0744 - 

60000/60000 [==============================] - 65s 1ms/step - loss: 0.0266 - acc: 0.9941 - val_loss: 0.1201 - val_acc: 0.9826
Epoch 60/115
60000/60000 [==============================] - 66s 1ms/step - loss: 0.0244 - acc: 0.9942 - val_loss: 0.1132 - val_acc: 0.9827
Epoch 61/115
60000/60000 [==============================] - 90s 1ms/step - loss: 0.0267 - acc: 0.9934 - val_loss: 0.1153 - val_acc: 0.9834
Epoch 62/115
60000/60000 [==============================] - 65s 1ms/step - loss: 0.0251 - acc: 0.9942 - val_loss: 0.1141 - val_acc: 0.9843
Epoch 63/115
60000/60000 [==============================] - 65s 1ms/step - loss: 0.0270 - acc: 0.9937 - val_loss: 0.1092 - val_acc: 0.9840
Epoch 64/115
60000/60000 [==============================] - 65s 1ms/step - loss: 0.0234 - acc: 0.9944 - val_loss: 0.1198 - val_acc: 0.9839
Epoch 65/115
60000/60000 [==============================] - 65s 1ms/step - loss: 0.0274 - acc: 0.9941 - val_loss: 0.1093 - val_acc: 0.9843
Epoch 66/115
60000/60000 [==============

In [52]:
import pandas as pd
test = pd.read_csv("test.csv")

In [53]:
print(test.shape)

(28000, 784)


In [54]:
y_pred = model.predict(test)

In [55]:
print(y_pred)

[[0. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 1. ... 0. 0. 0.]]


In [56]:
result= [0]*28000

for y, item in enumerate(y_pred):
    for x, name in enumerate(item):
        if name == 1:
            result[y] = x
            break

In [57]:
print(result[0:12])

[2, 0, 9, 2, 3, 2, 0, 3, 0, 3, 5, 2]


In [58]:
print(len(result))
submit_list = result

28000


In [59]:
import numpy as np
imgid = np.array(np.arange(1,28001)).astype(int)
result = pd.DataFrame(submit_list, imgid, columns = ["Label"])
result.index.name = "ImageId"
result.to_csv("digits_result26.csv")

In [60]:
print(result)

         Label
ImageId       
1            2
2            0
3            9
4            2
5            3
6            2
7            0
8            3
9            0
10           3
11           5
12           2
13           4
14           0
15           4
16           3
17           3
18           1
19           9
20           0
21           9
22           1
23           2
24           5
25           7
26           4
27           2
28           7
29           8
30           7
...        ...
27971        5
27972        0
27973        4
27974        8
27975        0
27976        3
27977        6
27978        2
27979        1
27980        9
27981        3
27982        2
27983        2
27984        0
27985        4
27986        5
27987        2
27988        2
27989        9
27990        6
27991        7
27992        6
27993        2
27994        9
27995        7
27996        9
27997        7
27998        3
27999        9
28000        2

[28000 rows x 1 columns]
