In [58]:
import keras
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.optimizers import RMSprop

In [59]:
from keras.datasets import mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()

In [60]:
batch_size = 128
epochs = 40
num_classes = 10

In [61]:
x_train = x_train.reshape(60000, 784)
x_test = x_test.reshape(10000, 784)

In [62]:
x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train /= 255
x_test /= 255

In [63]:
y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)

In [67]:
model  = Sequential()

In [68]:
model.add(Dense(512, activation = 'relu', input_shape = (784,)))
model.add(Dropout(0.2))
model.add(Dense(512, activation = 'relu'))
model.add(Dropout(0.2))
model.add(Dense(512, activation = 'relu'))
model.add(Dropout(0.2))
model.add(Dense(10, activation='softmax'))

model.summary()

model.compile(loss='categorical_crossentropy', optimizer=RMSprop(), metrics=['accuracy'])

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_41 (Dense)             (None, 512)               401920    
_________________________________________________________________
dropout_33 (Dropout)         (None, 512)               0         
_________________________________________________________________
dense_42 (Dense)             (None, 512)               262656    
_________________________________________________________________
dropout_34 (Dropout)         (None, 512)               0         
_________________________________________________________________
dense_43 (Dense)             (None, 512)               262656    
_________________________________________________________________
dropout_35 (Dropout)         (None, 512)               0         
_________________________________________________________________
dense_44 (Dense)             (None, 10)                5130      
Total para

In [69]:
history = model.fit(x_train, y_train
                    , batch_size = batch_size
                    , epochs = epochs
                    , verbose = 1
                    , validation_data=(x_test, y_test))

Train on 60000 samples, validate on 10000 samples
Epoch 1/40
60000/60000 [==============================] - 105s 2ms/step - loss: 0.2696 - acc: 0.9158 - val_loss: 0.1105 - val_acc: 0.9682
Epoch 2/40
60000/60000 [==============================] - 94s 2ms/step - loss: 0.1142 - acc: 0.9660 - val_loss: 0.0964 - val_acc: 0.9714
Epoch 3/40
60000/60000 [==============================] - 94s 2ms/step - loss: 0.0882 - acc: 0.9743 - val_loss: 0.0796 - val_acc: 0.9782
Epoch 4/40
60000/60000 [==============================] - 83s 1ms/step - loss: 0.0757 - acc: 0.9786 - val_loss: 0.0818 - val_acc: 0.9769
Epoch 5/40
60000/60000 [==============================] - 77s 1ms/step - loss: 0.0684 - acc: 0.9814 - val_loss: 0.0815 - val_acc: 0.9812
Epoch 6/40
60000/60000 [==============================] - 77s 1ms/step - loss: 0.0590 - acc: 0.9839 - val_loss: 0.0983 - val_acc: 0.9803
Epoch 7/40
60000/60000 [==============================] - 77s 1ms/step - loss: 0.0585 - acc: 0.9848 - val_loss: 0.1003 - val_ac

In [70]:
import pandas as pd
test = pd.read_csv("test.csv")

In [71]:
print(test.shape)

(28000, 784)


In [72]:
y_pred = model.predict(test)

In [73]:
print(y_pred)

[[0. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 1. ... 0. 0. 0.]]


In [74]:
result= [0]*28000

for y, item in enumerate(y_pred):
    for x, name in enumerate(item):
        if name == 1:
            result[y] = x
            break

In [75]:
print(result[0:12])

[2, 0, 9, 0, 3, 7, 0, 3, 0, 3, 5, 7]


In [76]:
print(len(result))
submit_list = result

28000


In [77]:
import numpy as np
imgid = np.array(np.arange(1,28001)).astype(int)
result = pd.DataFrame(submit_list, imgid, columns = ["Label"])
result.index.name = "ImageId"
result.to_csv("digits_result06.csv")

In [78]:
print(result)

         Label
ImageId       
1            2
2            0
3            9
4            0
5            3
6            7
7            0
8            3
9            0
10           3
11           5
12           7
13           4
14           0
15           4
16           3
17           3
18           1
19           9
20           0
21           9
22           1
23           1
24           5
25           7
26           4
27           2
28           7
29           4
30           7
...        ...
27971        5
27972        0
27973        4
27974        8
27975        0
27976        3
27977        6
27978        0
27979        1
27980        9
27981        3
27982        1
27983        1
27984        0
27985        4
27986        5
27987        2
27988        2
27989        9
27990        6
27991        7
27992        6
27993        1
27994        9
27995        7
27996        9
27997        7
27998        3
27999        9
28000        2

[28000 rows x 1 columns]
