In [70]:
import keras
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.optimizers import RMSprop

In [71]:
from keras.datasets import mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()

In [72]:
batch_size = 128
epochs = 50
num_classes = 10

In [73]:
x_train = x_train.reshape(60000, 784)
x_test = x_test.reshape(10000, 784)

In [74]:
x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train /= 255
x_test /= 255

In [75]:
y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)

In [76]:
model  = Sequential()

In [77]:
model.add(Dense(512, activation = 'relu', input_shape = (784,)))
model.add(Dropout(0.2))
model.add(Dense(512, activation = 'relu'))
model.add(Dropout(0.2))
model.add(Dense(10, activation='softmax'))

model.summary()

model.compile(loss='categorical_crossentropy', optimizer=RMSprop(lr=0.0009), metrics=['accuracy'])

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_31 (Dense)             (None, 512)               401920    
_________________________________________________________________
dropout_21 (Dropout)         (None, 512)               0         
_________________________________________________________________
dense_32 (Dense)             (None, 512)               262656    
_________________________________________________________________
dropout_22 (Dropout)         (None, 512)               0         
_________________________________________________________________
dense_33 (Dense)             (None, 10)                5130      
Total params: 669,706
Trainable params: 669,706
Non-trainable params: 0
_________________________________________________________________


In [78]:
history = model.fit(x_train, y_train
                    , batch_size = batch_size
                    , epochs = epochs
                    , verbose = 1
                    , validation_data=(x_test, y_test))

Train on 60000 samples, validate on 10000 samples
Epoch 1/50
60000/60000 [==============================] - 76s 1ms/step - loss: 0.2516 - acc: 0.9233 - val_loss: 0.1109 - val_acc: 0.9663
Epoch 2/50
60000/60000 [==============================] - 69s 1ms/step - loss: 0.1024 - acc: 0.9686 - val_loss: 0.0803 - val_acc: 0.9759
Epoch 3/50
60000/60000 [==============================] - 69s 1ms/step - loss: 0.0740 - acc: 0.9776 - val_loss: 0.0842 - val_acc: 0.9763
Epoch 4/50
60000/60000 [==============================] - 66s 1ms/step - loss: 0.0596 - acc: 0.9823 - val_loss: 0.0760 - val_acc: 0.9790
Epoch 5/50
60000/60000 [==============================] - 67s 1ms/step - loss: 0.0516 - acc: 0.9848 - val_loss: 0.0710 - val_acc: 0.9811
Epoch 6/50
60000/60000 [==============================] - 69s 1ms/step - loss: 0.0417 - acc: 0.9873 - val_loss: 0.0749 - val_acc: 0.9815
Epoch 7/50
60000/60000 [==============================] - 59s 980us/step - loss: 0.0355 - acc: 0.9889 - val_loss: 0.0840 - val_a

In [90]:
import pandas as pd
test = pd.read_csv("test.csv")

In [91]:
print(test.shape)

(28000, 784)


In [92]:
y_pred = model.predict(test)

In [93]:
print(y_pred)

[[0. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 1. ... 0. 0. 0.]]


In [94]:
result= [0]*28000

for y, item in enumerate(y_pred):
    for x, name in enumerate(item):
        if name == 1:
            result[y] = x
            break

In [95]:
print(result[0:12])

[2, 0, 9, 0, 3, 7, 0, 3, 0, 3, 5, 7]


In [96]:
print(len(result))
submit_list = result

28000


In [97]:
import numpy as np
imgid = np.array(np.arange(1,28001)).astype(int)
result = pd.DataFrame(submit_list, imgid, columns = ["Label"])
result.index.name = "ImageId"
result.to_csv("digits_result10.csv")

In [98]:
print(result)

         Label
ImageId       
1            2
2            0
3            9
4            0
5            3
6            7
7            0
8            3
9            0
10           3
11           5
12           7
13           4
14           0
15           4
16           3
17           3
18           1
19           9
20           0
21           9
22           1
23           1
24           5
25           7
26           4
27           2
28           7
29           4
30           7
...        ...
27971        5
27972        0
27973        4
27974        8
27975        0
27976        3
27977        6
27978        0
27979        1
27980        9
27981        3
27982        1
27983        1
27984        0
27985        4
27986        5
27987        2
27988        2
27989        9
27990        6
27991        7
27992        6
27993        1
27994        9
27995        7
27996        9
27997        7
27998        3
27999        9
28000        2

[28000 rows x 1 columns]
