In [1]:
#バッチごとに先に正規化

In [2]:
import keras
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout, BatchNormalization, Activation
from keras.optimizers import RMSprop

Using TensorFlow backend.


In [3]:
from keras.datasets import mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()

In [4]:
#batch_size = 128
#epochs = 50
num_classes = 10

In [5]:
x_train = x_train.reshape(60000, 784)
x_test = x_test.reshape(10000, 784)

In [6]:
x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train /= 255
x_test /= 255

In [7]:
y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)

In [44]:
activation = "relu"
out_dim = 512
dropout = 0.2
batch_size = 128
epochs = 115

In [61]:
model  = Sequential()
model.add(Dense(512, activation= 'relu', input_shape = (784,)))
model.add(Dropout(dropout))
model.add(Dense(512,activation= 'relu')) 
model.add(Dropout(dropout))
model.add(BatchNormalization())
model.add(Dense(10, activation = 'softmax'))
model.summary()
model.compile(loss='categorical_crossentropy', optimizer=RMSprop(lr=0.0009), metrics=['accuracy'])

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_18 (Dense)             (None, 512)               401920    
_________________________________________________________________
dropout_12 (Dropout)         (None, 512)               0         
_________________________________________________________________
dense_19 (Dense)             (None, 512)               262656    
_________________________________________________________________
dropout_13 (Dropout)         (None, 512)               0         
_________________________________________________________________
batch_normalization_8 (Batch (None, 512)               2048      
_________________________________________________________________
dense_20 (Dense)             (None, 10)                5130      
Total params: 671,754
Trainable params: 670,730
Non-trainable params: 1,024
_________________________________________________________________


In [62]:
history = model.fit(x_train, y_train
                   , batch_size = batch_size
                    , epochs = epochs
                    , verbose = 1
                    , validation_data=(x_test, y_test))

Train on 60000 samples, validate on 10000 samples
Epoch 1/115
60000/60000 [==============================] - 84s 1ms/step - loss: 0.2346 - acc: 0.9275 - val_loss: 0.1246 - val_acc: 0.9627
Epoch 2/115
60000/60000 [==============================] - 69s 1ms/step - loss: 0.1098 - acc: 0.9664 - val_loss: 0.0972 - val_acc: 0.9735
Epoch 3/115
60000/60000 [==============================] - 73s 1ms/step - loss: 0.0799 - acc: 0.9756 - val_loss: 0.0655 - val_acc: 0.9814
Epoch 4/115
60000/60000 [==============================] - 85s 1ms/step - loss: 0.0641 - acc: 0.9798 - val_loss: 0.0684 - val_acc: 0.9788
Epoch 5/115
60000/60000 [==============================] - 83s 1ms/step - loss: 0.0536 - acc: 0.9834 - val_loss: 0.0686 - val_acc: 0.9796
Epoch 6/115
60000/60000 [==============================] - 52s 875us/step - loss: 0.0456 - acc: 0.9859 - val_loss: 0.0580 - val_acc: 0.9833
Epoch 7/115
60000/60000 [==============================] - 65s 1ms/step - loss: 0.0378 - acc: 0.9881 - val_loss: 0.0661 

KeyboardInterrupt: 

In [48]:
import pandas as pd
test = pd.read_csv("test.csv")

In [49]:
print(test.shape)

(28000, 784)


In [50]:
y_pred = model.predict(test)

In [51]:
print(y_pred)

[[0. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 1. ... 0. 0. 0.]]


In [52]:
result= [0]*28000

for y, item in enumerate(y_pred):
    for x, name in enumerate(item):
        if name == 1:
            result[y] = x
            break

In [53]:
print(result[0:12])

[2, 0, 9, 9, 3, 7, 0, 3, 0, 3, 5, 7]


In [54]:
print(len(result))
submit_list = result

28000


In [55]:
import numpy as np
imgid = np.array(np.arange(1,28001)).astype(int)
result = pd.DataFrame(submit_list, imgid, columns = ["Label"])
result.index.name = "ImageId"
result.to_csv("digits_result27.csv")

In [56]:
print(result)

         Label
ImageId       
1            2
2            0
3            9
4            9
5            3
6            7
7            0
8            3
9            0
10           3
11           5
12           7
13           4
14           0
15           4
16           3
17           3
18           1
19           9
20           0
21           9
22           1
23           8
24           5
25           7
26           4
27           2
28           7
29           8
30           7
...        ...
27971        5
27972        0
27973        4
27974        8
27975        0
27976        3
27977        6
27978        0
27979        1
27980        9
27981        3
27982        1
27983        8
27984        0
27985        4
27986        5
27987        2
27988        2
27989        9
27990        6
27991        7
27992        6
27993        1
27994        9
27995        7
27996        9
27997        7
27998        3
27999        9
28000        2

[28000 rows x 1 columns]
