In [1]:
import keras
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.optimizers import RMSprop

Using TensorFlow backend.


In [2]:
from keras.datasets import mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()

In [3]:
batch_size = 128
epochs = 20
num_classes = 10

In [4]:
x_train = x_train.reshape(60000, 784)
x_test = x_test.reshape(10000, 784)

In [5]:
x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train /= 255
x_test /= 255

In [6]:
y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)

In [7]:
model  = Sequential()

In [8]:
model.add(Dense(512, activation = 'relu', input_shape = (784,)))
model.add(Dropout(0.2))
model.add(Dense(512, activation = 'relu'))
model.add(Dropout(0.2))
model.add(Dense(10, activation='softmax'))

model.summary()

model.compile(loss='categorical_crossentropy', optimizer=RMSprop(), metrics=['accuracy'])

Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 512)               401920    
_________________________________________________________________
dropout_1 (Dropout)          (None, 512)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 512)               262656    
_________________________________________________________________
dropout_2 (Dropout)          (None, 512)               0         
_________________________________________________________________
dense_3 (Dense)              (None, 10)                5130      
Total params: 669,706
Trainable params: 669,706
Non-trainable params: 0
_______________

In [9]:
history = model.fit(x_train, y_train
                    , batch_size = batch_size
                    , epochs = epochs
                    , verbose = 1
                    , validation_data=(x_test, y_test))

Instructions for updating:
Use tf.cast instead.
Train on 60000 samples, validate on 10000 samples
Epoch 1/20
60000/60000 [==============================] - 83s 1ms/step - loss: 0.2448 - acc: 0.9233 - val_loss: 0.1299 - val_acc: 0.9590
Epoch 2/20
60000/60000 [==============================] - 71s 1ms/step - loss: 0.1031 - acc: 0.9683 - val_loss: 0.0928 - val_acc: 0.9739
Epoch 3/20
60000/60000 [==============================] - 70s 1ms/step - loss: 0.0743 - acc: 0.9772 - val_loss: 0.0916 - val_acc: 0.9724
Epoch 4/20
60000/60000 [==============================] - 70s 1ms/step - loss: 0.0604 - acc: 0.9822 - val_loss: 0.0789 - val_acc: 0.9801
Epoch 5/20
60000/60000 [==============================] - 67s 1ms/step - loss: 0.0511 - acc: 0.9844 - val_loss: 0.0886 - val_acc: 0.9784
Epoch 6/20
60000/60000 [==============================] - 58s 968us/step - loss: 0.0425 - acc: 0.9872 - val_loss: 0.0792 - val_acc: 0.9819
Epoch 7/20
60000/60000 [==============================] - 58s 964us/step - los

In [10]:
import pandas as pd
test = pd.read_csv("test.csv")

In [11]:
print(test.shape)

(28000, 784)


In [12]:
y_pred = model.predict(test)

In [13]:
print(y_pred)

[[0. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 1. ... 0. 0. 0.]]


In [14]:
result= [0]*28000

for y, item in enumerate(y_pred):
    for x, name in enumerate(item):
        if name == 1:
            result[y] = x
            break

In [15]:
print(result[0:12])

[2, 0, 9, 0, 3, 7, 0, 3, 0, 3, 5, 7]


In [16]:
print(len(result))
submit_list = result

28000


In [17]:
import numpy as np
imgid = np.array(np.arange(1,28001)).astype(int)
result = pd.DataFrame(submit_list, imgid, columns = ["Label"])
result.index.name = "ImageId"
result.to_csv("digits_result07.csv")

In [18]:
print(result)

         Label
ImageId       
1            2
2            0
3            9
4            0
5            3
6            7
7            0
8            3
9            0
10           3
11           5
12           7
13           4
14           0
15           4
16           3
17           3
18           1
19           9
20           0
21           9
22           1
23           1
24           5
25           7
26           4
27           2
28           7
29           4
30           7
...        ...
27971        5
27972        0
27973        4
27974        8
27975        0
27976        3
27977        6
27978        0
27979        1
27980        9
27981        3
27982        1
27983        1
27984        0
27985        4
27986        5
27987        2
27988        2
27989        9
27990        6
27991        7
27992        6
27993        1
27994        9
27995        7
27996        9
27997        7
27998        3
27999        9
28000        2

[28000 rows x 1 columns]
